### ISSUE TITLE
ros2_aruco: stderr output

### ISSUE THREAD

**Issue by izeemeen** [JMU-ROBOTICS-VIVA/ros2_aruco#13]
Hello!
I try to build ros2_aruco and got this error:

**sudo python3 setup.py install**

running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing ros2_aruco.egg-info/PKG-INFO
writing dependency_links to ros2_aruco.egg-info/dependency_links.txt
writing entry points to ros2_aruco.egg-info/entry_points.txt
writing requirements to ros2_aruco.egg-info/requires.txt
writing top-level names to ros2_aruco.egg-info/top_level.txt
reading manifest file 'ros2_aruco.egg-info/SOURCES.txt'
writing manifest file 'ros2_aruco.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
creating build/bdist.linux-aarch64/egg
creating build/bdist.linux-aarch64/egg/ros2_aruco
copying build/lib/ros2_aruco/__init__.py -> build/bdist.linux-aarch64/egg/ros2_aruco
copying build/lib/ros2_aruco/aruco_node.py -> build/bdist.linux-aarch64/egg/ros2_aruco
copying build/lib/ros2_aruco/aruco_generate_marker.py -> build/bdist.linux-aarch64/egg/ros2_aruco
byte-compiling build/bdist.linux-aarch64/egg/ros2_aruco/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-aarch64/egg/ros2_aruco/aruco_node.py to aruco_node.cpython-310.pyc
byte-compiling build/bdist.linux-aarch64/egg/ros2_aruco/aruco_generate_marker.py to aruco_generate_marker.cpython-310.pyc
installing package data to build/bdist.linux-aarch64/egg
running install_data
creating build/bdist.linux-aarch64/egg/share
creating build/bdist.linux-aarch64/egg/share/ament_index
creating build/bdist.linux-aarch64/egg/share/ament_index/resource_index
creating build/bdist.linux-aarch64/egg/share/ament_index/resource_index/packages
copying resource/ros2_aruco -> build/bdist.linux-aarch64/egg/share/ament_index/resource_index/packages
creating build/bdist.linux-aarch64/egg/share/ros2_aruco
copying package.xml -> build/bdist.linux-aarch64/egg/share/ros2_aruco
creating build/bdist.linux-aarch64/egg/share/ros2_aruco/launch
copying launch/aruco_recognition.launch.py -> build/bdist.linux-aarch64/egg/share/ros2_aruco/launch
creating build/bdist.linux-aarch64/egg/share/ros2_aruco/config
copying config/aruco_parameters.yaml -> build/bdist.linux-aarch64/egg/share/ros2_aruco/config
creating build/bdist.linux-aarch64/egg/EGG-INFO
copying ros2_aruco.egg-info/PKG-INFO -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ros2_aruco.egg-info/SOURCES.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ros2_aruco.egg-info/dependency_links.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ros2_aruco.egg-info/entry_points.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ros2_aruco.egg-info/requires.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ros2_aruco.egg-info/top_level.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying ros2_aruco.egg-info/zip-safe -> build/bdist.linux-aarch64/egg/EGG-INFO
creating 'dist/ros2_aruco-0.1.0-py3.10.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing ros2_aruco-0.1.0-py3.10.egg
Removing /usr/local/lib/python3.10/dist-packages/ros2_aruco-0.1.0-py3.10.egg
Copying ros2_aruco-0.1.0-py3.10.egg to /usr/local/lib/python3.10/dist-packages
ros2-aruco 0.1.0 is already the active version in easy-install.pth
Installing aruco_generate_marker script to /usr/lib/ros2_aruco
Installing aruco_node script to /usr/lib/ros2_aruco

Installed /usr/local/lib/python3.10/dist-packages/ros2_aruco-0.1.0-py3.10.egg
Processing dependencies for ros2-aruco==0.1.0
Searching for setuptools==59.6.0
Best match: setuptools 59.6.0
Adding setuptools 59.6.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for ros2-aruco==0.1.0

**rosdep install --from-paths src --ignore-src -r -y**

#All required rosdeps installed successfully

**colcon build --symlink-install**

Starting >>> ros2_aruco
Starting >>> ros2_aruco_interfaces       
--- stderr: ros2_aruco                                                                       
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ros2_aruco [21.6s]
Finished <<< ros2_aruco_interfaces [31.7s]                       

Summary: 2 packages finished [35.8s]
  1 package had stderr output: ros2_aruco

How can I resolve this error?

**Comment by spragunr** [comment]
It looks like the `colcon build` command is successfully building the package.  The warnings in stderr are a known issue with building ROS2 python packages. 

https://github.com/colcon/colcon-core/issues/454

You can ignore them or suppress them.

**Comment by izeemeen** [comment]
Thanks for the answer, @spragunr !
Now after launching: **ros2 launch ros2_aruco aruco_recognition.launch.py**
I get the following error:

[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2024-07-17-10-08-05-815639-ubuntu-1579
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [aruco_node-1]: process started with pid [1580]
[aruco_node-1] [INFO] [1721210891.213555239] [aruco_node]: Marker size: 0.055
[aruco_node-1] [INFO] [1721210891.220722390] [aruco_node]: Marker type: DICT_5X5_250
[aruco_node-1] [INFO] [1721210891.228793033] [aruco_node]: Image topic: /image_raw
[aruco_node-1] [INFO] [1721210891.235751487] [aruco_node]: Image info topic: /camera_info
[aruco_node-1] Traceback (most recent call last):
[aruco_node-1]   File "/home/ubuntu/aruco_ros2_ws/install/ros2_aruco/lib/ros2_aruco/aruco_node", line 33, in <module>
[aruco_node-1]     sys.exit(load_entry_point('ros2-aruco==0.1.0', 'console_scripts', 'aruco_node')())
[aruco_node-1]   File "/home/ubuntu/aruco_ros2_ws/install/ros2_aruco/lib/python3.10/site-packages/ros2_aruco/aruco_node.py", line 214, in main
[aruco_node-1]     node = ArucoNode()
[aruco_node-1]   File "/home/ubuntu/aruco_ros2_ws/install/ros2_aruco/lib/python3.10/site-packages/ros2_aruco/aruco_node.py", line 148, in __init__
[aruco_node-1]     self.aruco_dictionary = cv2.aruco.Dictionary_get(dictionary_id)
[aruco_node-1] AttributeError: module 'cv2.aruco' has no attribute 'Dictionary_get'. Did you mean: 'Dictionary'?
[ERROR] [aruco_node-1]: process has died [pid 1580, exit code 1, cmd '/home/ubuntu/aruco_ros2_ws/install/ros2_aruco/lib/ros2_aruco/aruco_node --ros-args --params-file /home/ubuntu/aruco_ros2_ws/install/ros2_aruco/share/ros2_aruco/config/aruco_parameters.yaml'].


What could this be connected with, maybe with the open version?

**Comment by jkaniuka** [comment]
@izeemeen There has been a change in OpenCV API since 4.7.x - you can read more here https://stackoverflow.com/questions/74964527/attributeerror-module-cv2-aruco-has-no-attribute-dictionary-get 

As a quick-fix I recommend you to install older version of `opencv-contrib-python` library. I'm using it with **v4.6.0.66** and it works fine. You can use the following command:

```bash
sudo pip3 install opencv-contrib-python==4.6.0.66
```

**Comment by jkaniuka** [comment]
If you don't want to use older version of OpenCV, you can checkout to `opencv_4.7` branch of this repo :wink:
